# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: violence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'violence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eviolence.proto\x12\x08violence\"O\n\x0c\x46rameRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x11\n\tframe_idx\x18\x02 \x01(\x03\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xec\x01\n\x0e\x44\x65tectResponse\x12\x11\n\tframe_idx\x18\x01 \x01(\x03\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x12\r\n\x05\x61lert\x18\x03 \x01(\x08\x12\r\n\x05label\x18\x04 \x01(\t\x12\x12\n\nboxes_flat\x18\x05 \x03(\x02\x12\r\n\x05\x63onfs\x18\x06 \x03(\x02\x12\x0e\n\x06roi_x1\x18\x07 \x01(\x02\x12\x0e\n\x06roi_y1\x18\x08 \x01(\x02\x12\x0e\n\x06roi_x2\x18\t \x01(\x02\x12\x0e\n\x06roi_y2\x18\n \x01(\x02\x12\x0f\n\x07small_w\x18\x0b \x01(\x05\x12\x0f\n\x07small_h\x18\x0c \x01(\x05\x12\x0f\n\x07has_roi\x18\r \x01(\x08\x32X\n\x10ViolenceDetector\x12\x44\n\x0c\x44\x65tectStream\x12\x16.violence.FrameRequest\x1a\x18.violence.DetectResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'violence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=28
  _globals['_FRAMEREQUEST']._serialized_end=107
  _globals['_DETECTRESPONSE']._serialized_start=110
  _globals['_DETECTRESPONSE']._serialized_end=346
  _globals['_VIOLENCEDETECTOR']._serialized_start=348
  _globals['_VIOLENCEDETECTOR']._serialized_end=436
# @@protoc_insertion_point(module_scope)
